mode: mode_512
framework: onnx
device: cpu

weights:
  pytorch: trained_model/scrfd_10g.pth
  onnx: trained_model/scrfd_500.onnx

mode_512:
  checkpoint: trained_model_03.t7
  size: 512
  saveFolder: result_512
  windowName: Result Mode 512

mode_1024:
  checkpoint: trained_model_1024_03.t7
  size: 1024
  saveFolder: result_1024
  windowName: Result Mode 1024

saveVisualize: False
lightFolder: data/example_light/rotate_light_2/txt/
path_image: data/images_test/timi2.png
modelFolder: trained_model/
showResult: False
saveResult: False